name: Rust

on: [push, pull_request]

jobs:

  Pretty:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run Clippy
      run: cargo clippy -- -D warnings
  
  Build:
    runs-on: ubuntu-latest
    needs: Pretty
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose

  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests for mutex
      run: cargo test mutex
    - name: Run tests for condvars
      run: cargo test cond