name: Rust

on: [push, pull_request]

jobs:

  Pretty:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run Clippy
      run: cargo clippy -- -D clippy::pedantic
  
  Build:
    runs-on: ubuntu-latest
    needs: Pretty
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose

  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: cargo test --verbose

  Testing-TSAN:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Switch to nightly
      run: rustup default nightly
    - name: Run tests
      run: RUSTFLAGS="-Zsanitizer=thread" cargo test --verbose --target x86_64-unknown-linux-gnu

  Testing-LSAN:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Switch to nightly
      run: rustup default nightly
    - name: Run tests
      run: RUSTFLAGS="-Zsanitizer=leak" cargo test --verbose --target x86_64-unknown-linux-gnu

  Testing-MSAN:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Switch to nightly
      run: rustup default nightly
    - name: Run tests
      run: RUSTFLAGS="-Zsanitizer=memory" cargo test --verbose --target x86_64-unknown-linux-gnu

  Testing-ASAN:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Switch to nightly
      run: rustup default nightly
    - name: Run tests
      run: RUSTFLAGS="-Zsanitizer=address" cargo test --verbose --target x86_64-unknown-linux-gnu


      