name: Rust

on: [push, pull_request]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
  clippy:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - uses: actions/checkout@v3
    - name: Check folder
      run: echo "$(ls -1)" >> $GITHUB_OUTPUT
    - name: Run Clippy
      run: cargo clippy -- -D warnings
  
  build:
    runs-on: ubuntu-latest
    needs: clippy
    steps:
    - name: Build
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run tests
      run: cargo test --verbose